services:
  server:
    image: bykof/pokecoin-server:latest
    ports:
      - 3000:3000
    environment:
      - PRODUCTION=false
      - MONGODB_URL=mongodb://mongodb/pokecoin
      - PORT=3000
      - DEFAULT_REWARD=1
      - DEFAULT_PACKAGE_COST=25
      - JWT_SECRET=abcdef
      - POW_DIFFICULTY=6
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    # Uncomment volumes block, so that data isnt stored after restart
    volumes:
      - ./.mongo:/data/db
